---
# tasks file for update_package_cache

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ update_package_cache_cache_valid_time  }}"
  when:
    - ansible_pkg_mgr == "apt"

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: yes
  when:
    - ansible_pkg_mgr == "yum"
